baseURL: 'https://mudassir-nawaz.github.io/Ryanlebon/'
languageCode: 'en-us'
title: 'Ryan Lebon'

params:
    logo: "/images/logo.png"
    plugins:
        css:
        - link: css/bootstrap.min.css
        - link: css/main.css
        - link: css/font-awesome.min.css
        - link: css/animate.css
        - link: themefisher-font/style.css
menus:
  main: # Main Menu
  - name: Home
    url: "/"
    weight: "1"
  - name: About
    url: "/about/"
    weight: "10"
  - name: Service
    url: "/service/"
    weight: "11"