baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Ryan Lebon'

[Params]
    logo = "images/logo.png"

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 2

[[menu.main]]
name = "About"
URL = "/about/"
weight = 3

[[menu.main]]
name = "Service"
URL = "/service/"
weight = 3